### ISSUE TITLE
Unterscheide rein vegane Lokalitäten von Lokalitäten mit veganem Angebot

### ISSUE THREAD

**Issue by piratenpanda** [piratenpanda/veggiekarte#1]
Lösbar über diet:vegan=yes und diet:vegan=only. Muss in refresh.py angepasst werden

**Comment by piratenpanda** [comment]
Will be implemented soon

**Comment by KristjanESPERANTO** [comment]
Did you reopen this issue on purpose?

**Comment by piratenpanda** [comment]
No, sorry. The dependabot stuff confused me
