### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by impeira** [piratenpanda/veggiekarte#104]
I added a lot of vegetarian/vegan restaurants in the last 3 month and I think none of them is displayed on the veggiekarte.
https://overpass-turbo.eu/s/1iI5 vs. https://www.veggiekarte.de/?lang=de#12.0000/50.9867/11.0437

**Comment by piratenpanda** [comment]
Thanks for the bug report. I think I found the issue. Working on a fix

**Comment by KristjanESPERANTO** [comment]
Oh, crap. I watched it at the same time and I didn't saw your response @piratenpanda.

We obviously have a timeout problem. What do you think of my approach (#105)?

**Comment by piratenpanda** [comment]
Was a mistake in the crontab on my side. Should be fixed now

**Comment by piratenpanda** [comment]
We should still increase the timeout. So if you could do another PR without new data I'll merge it

**Comment by Strubbl** [comment]
Is this issue still a thing so that the data is not up to date? in the layer legend on the website i still see the date 23 May 2022.

**Comment by piratenpanda** [comment]
Well this is embarrassing. I'll look into it after work

**Comment by piratenpanda** [comment]
Hopefully the last fix necessary. So sorry about this

**Comment by Strubbl** [comment]
Now, it looks like the updates are done daily instead of hourly. Is this intentional? If yes, the docu needs a small update in https://github.com/piratenpanda/veggiekarte/blob/main/locales/en.json#L18

**Comment by piratenpanda** [comment]
It's even done half-hourly now. The daily jumps were only due to my incompetence again.. Hope all is fine now for good
