### ISSUE TITLE
iPhone issues

### ISSUE THREAD

**Issue by piratenpanda** [piratenpanda/veggiekarte#106]
Could some iPhone user maybe confirm or reproduce the issue? It works fine on my Android smartphone:
https://mastodon.art/@Linda/109013465072203274

**Comment by KristjanESPERANTO** [comment]
I don't have an iPhone either, but a friend was able to confirm the issue: Some buttons are missing on the right side.
![signal-2022-09-19-184352](https://user-images.githubusercontent.com/35647502/191070213-e4314fec-ef99-432d-a1eb-41bd2d3f8dcf.jpeg)
