### ISSUE TITLE
shouldn't show disused: restaurants

### ISSUE THREAD

**Issue by andyli** [piratenpanda/veggiekarte#109]
I noticed that veggiekarte shows restaurants that are tagged with `disused:`, e.g. node 9429821162 (Veggie Hut, `disused:amenity=restaurant`).

`disused:` items are hidden in most OSM viewers. It would be better to let OpenVegeMap uses the same behaviour.

**Comment by KristjanESPERANTO** [comment]
@andyli: Thanks for pointing that out! :slightly_smiling_face: Places like this will no longer appear. You may have to clear your cache for the change to take effect.

**Comment by andyli** [comment]
Thanks! That was pretty fast :)
