### ISSUE TITLE
Improve colors of icons and clustering

### ISSUE THREAD

**Issue by codedust** [piratenpanda/veggiekarte#11]
Different colors for different types of food would be great. E.g. something like:
- blue for `vegetarian:yes` and `vegan:yes`, but not `vegetarian:only` or `vegan:only`
- yellow for `vegetarian:only`, but not `vegan:only`
- green for `vegan:only`

The color of the clustering should not match any of the used colors from above to prevent confusion.

**Comment by piratenpanda** [comment]
Agreed

**Comment by severoraz** [comment]
Is the color legend shown somewhere? I am not very profficient in German and  I couldn't find it.

**Comment by piratenpanda** [comment]
Currently green icons offer vegan food, normal brown is vegetarian. And the clustering color is the default of the cluster add-on for leaflet

**Comment by piratenpanda** [comment]
Which is a heat map basically

**Comment by piratenpanda** [comment]
Will add english text soon, sorry for the inconvenience.

**Comment by severoraz** [comment]
Thanks! But don't be sorry :smiley:

**Comment by KristjanESPERANTO** [comment]
Meanwhile we have changed the colors. Can we close this issue or does anyone have suggestions for other colors?

**Comment by piratenpanda** [comment]
I am fine with the icons and the heatmap coloring is also best usability in my opinion
