### ISSUE TITLE
The contact:facebook tag

### ISSUE THREAD

**Issue by mstuyts** [piratenpanda/veggiekarte#112]
The tag contact:facebook can contain the url of a locations Facebook page or the Facebook pagename.
https://wiki.openstreetmap.org/wiki/Key:contact:facebook

Currently the content of the contact:facebook tag is on veggiekarte shown as the Facebook page of a restaurant.  If this tag only contains the pagename, https://www.facebook.com/ should be added in front of the pagename.

Example of restaurant where only the pagename is used: https://www.openstreetmap.org/node/10003018464

**Comment by KristjanESPERANTO** [comment]
Thanks for the hint! Pagenames work now too :slightly_smiling_face: 

Here is the location you gave as an example: https://www.veggiekarte.de/?lang=en#19/51.20450/4.43513

**Comment by piratenpanda** [comment]
fixed by https://github.com/piratenpanda/veggiekarte/pull/114
