### ISSUE TITLE
Closed places

### ISSUE THREAD

**Issue by rouelibre1** [piratenpanda/veggiekarte#117]
A few weeks ago I have updated an amenity that closed, using the prefix `was:` and it still shows on the map

![image](https://user-images.githubusercontent.com/73238613/203823080-b70a9a39-7546-4f10-9189-defda9d189cd.png)

https://www.openstreetmap.org/node/8455588502

**Comment by piratenpanda** [comment]
We currently only check for the disused tag, see https://github.com/piratenpanda/veggiekarte/issues/109

**Comment by rouelibre1** [comment]
Thanks for the quick feedback! Would it be a good idea to extend this mechanism described in 109, as I believe there are different ways contributors prefix places that are now closed?

**Comment by piratenpanda** [comment]
I'll look into this later, should be a pretty easy fix. But in the end we should encourage correct tagging. I could not find the was tag on the while quickly searching for it. Has the community agreed on which one is the preferred solution?

**Comment by piratenpanda** [comment]
fixed by https://github.com/piratenpanda/veggiekarte/commit/412e83e43d84574428e3e005ad9d43f20ad10688
