### ISSUE TITLE
locations not showing on map

### ISSUE THREAD

**Issue by arbie65** [piratenpanda/veggiekarte#12]
Using Debian + Firefox 45.9.0 (esr) and Fedora 53.0.2 the website is only displaying the world map but no vegetarian or vegan locations.

**Comment by piratenpanda** [comment]
Should be fixed now. Say thank you to the people tagging viewpoints and postoffices with diet tags ;) I should think a way of automatically excluding this by default

**Comment by arbie65** [comment]
hi @piratenpanda it looks like this broke again

**Comment by piratenpanda** [comment]
will look at this, sry it took me so long..

**Comment by piratenpanda** [comment]
Just running the script worked fine. Don't know what went wrong. Will watch this for a while...

**Comment by piratenpanda** [comment]
running it again made them disappear again, strange, sry for the inconvenience
