### ISSUE TITLE
check_results.json is not updated

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#125]
Hi :slightly_smiling_face: 

`check_results.json` is still from January 14th. Accordingly, the data in [datacheck table](https://veggiekarte.de/datacheck/datacheck_table.html) is outdated.

Does the job for `datacheck.py` still work?

**Comment by piratenpanda** [comment]
Hi, should be fixed, sorry about that. Thanks for reminding me to be a better admin..

**Comment by KristjanESPERANTO** [comment]
I think you are a good admin. Taking care of such a project for years is not something that can be taken for granted :clap:

**Comment by piratenpanda** [comment]
Thank you :)

**Comment by KristjanESPERANTO** [comment]
Unfortunately it still doesn't work.

**Comment by piratenpanda** [comment]
When I run my script that the cronjob runs the python script starts fine so I don't understand the issue. I'll let it run manually and see what the error in the end is/will be.

**Comment by piratenpanda** [comment]
runs without throwing an error

**Comment by piratenpanda** [comment]
Obviously it's not working but I don't see why. Will check more

**Comment by piratenpanda** [comment]
Cron job runs fine, when I run the script it runs fine, so strange

**Comment by piratenpanda** [comment]
Still does not work even when putting the python script directly into cron

**Comment by piratenpanda** [comment]
Cron job runs, script started manually runs without errors, yet it only works when you manually run it..

**Comment by piratenpanda** [comment]
`@daily python3 /var/www/html/www.veggiekarte.de/datacheck/datacheck.py`

**Comment by KristjanESPERANTO** [comment]
Maybe it's because there are two cron jobs with python running at the same time? I think it might be worth trying to schedule this job at 12:30 am:

`30 0 * * *  python3 /var/www/html/www.veggiekarte.de/datacheck/datacheck.py`

**Comment by KristjanESPERANTO** [comment]
The cron job for the refresh script always happens on the hour, doesn't it?

**Comment by piratenpanda** [comment]
yes, let's try

**Comment by piratenpanda** [comment]
seems to work now, well this was stupid

**Comment by KristjanESPERANTO** [comment]
Nice that it works! 🎉 But I still don't fully understand it ^^
