### ISSUE TITLE
Allow to open the map with customized filter

### ISSUE THREAD

**Issue by Daniel6801** [piratenpanda/veggiekarte#130]
The map opens per default with all filters set. It would be great if the map can be opened so that it shows for example only vegan restaurants. One possible way may be to add a parameter to the URL like "?veganonly=yes&vegetarian=yes". This makes it possible to bookmark the page in the browser with such filter criteria.

**Comment by KristjanESPERANTO** [comment]
That's a good idea! :slightly_smiling_face: I don't have the time for this project at the moment, but would support the implementation if necessary.

**Comment by piratenpanda** [comment]
Moved to https://codeberg.org/piratenpanda/veggiekarte/issues/130
