### ISSUE TITLE
Other food issues

### ISSUE THREAD

**Issue by loviuz** [piratenpanda/veggiekarte#137]
Hi all,

have you ever thought of including types of intolerances, such as gluten intolerance, in the map?

**Comment by piratenpanda** [comment]
is this even mapped in osm?

**Comment by loviuz** [comment]
yes, with diet:gluten_free=yes/no/only:

https://wiki.openstreetmap.org/wiki/Key:diet:*

I have made a map for umap:

https://umap.openstreetmap.fr/it/map/locali-per-celiaci_927207#8/50.881/11.102

**Comment by piratenpanda** [comment]
Thanks. I think this is the scope for another map like the one you created as this is not "veggie" specific.
