### ISSUE TITLE
Keine Aktualisierung der POIs? 

### ISSUE THREAD

**Issue by Matthias84** [piratenpanda/veggiekarte#14]
Schon seit einigen Wochen erscheinen keinen neuen POIs, die aber richtig getaggt sind. Als Beispiel [Schwerin auf der OpenVegeMap](https://openvegemap.netlib.re/#zoom=15&lat=53.63321&lon=11.4199)

**Comment by piratenpanda** [comment]
Sorry, da muss ich irgendwie den cronjob kaputt gemacht haben. Sollte jetzt wieder laufen. Danke für die Info!
