### ISSUE TITLE
icon_transport_fuel_veggie

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#15]
I'm playing a little with the code. When I'm execute the python script I get an object in the `veganmap-data.js` with an icon name "icon_transport_fuel_veggie". But this isn't in the `veganmap-icons.js`.

I can't find where you get the image files for the icons. Otherwise I would have create a pull request.

`L.marker([39.91066, -76.7050208], {"title": "Rutter's Farm Store", icon: icon_transport_fuel_veggie}).bindPopup("<b>Rutter's Farm Store</b> <a href=\"http://openstreetmap.org/browse/node/5913090560\" target=\"_blank\">*</a><hr/>Leaders Heights Road 129<br/>website: <a href=\"https://www.rutters.com/\" target=\"_blank\">https://www.rutters.com/</a><br/><hr/>opening_hours: 24/7<br/>").addTo(markers);`

**Comment by KristjanESPERANTO** [comment]
Seems that sometimes (without changing the code) the same object gets an other icon: "icon_shopping_convenience_veggie".

`L.marker([39.91066, -76.7050208], {"title": "Rutter's Farm Store", icon: icon_shopping_convenience_veggie}).bindPopup("<b>Rutter's Farm Store</b> <a href=\"http://openstreetmap.org/browse/node/5913090560\" target=\"_blank\">*</a><hr/>Leaders Heights Road 129<br/>website: <a href=\"https://www.rutters.com/\" target=\"_blank\">https://www.rutters.com/</a><br/><hr/>opening_hours: 24/7<br/>").addTo(markers);`

**Comment by piratenpanda** [comment]
The icon mapping and selection happens in refresh.py https://github.com/piratenpanda/veggiekarte/blob/master/refresh.py

**Comment by KristjanESPERANTO** [comment]
Sorry, I mixed the icon name: `icon_transport_fuel_veggie` is not in the `veganmap-icons.js`. In this case the map stays empty.

**Comment by KristjanESPERANTO** [comment]
Okay, I fixed it and just created a pull request: https://github.com/piratenpanda/veggiekarte/pull/17

But I still wondering why you don't have this problem: Your `refresh.py` outputs `icon_shopping_convenience_veggie` [1] for the node 5913090560. But when I execute the (unchanged) `refresh.py` from your repository, I get `icon_transport_fuel_veggie`. Anyway this fixes the issue :-)

[1] https://veggiekarte.de/js/veganmap-data.js

**Comment by KristjanESPERANTO** [comment]
Thank you for the fast merge :-)
