### ISSUE TITLE
Transmit the data as JSON?

### ISSUE THREAD

**Issue by tuukka** [piratenpanda/veggiekarte#35]
To implement new features such as in #6, would you be willing to store and transmit the restaurant data in JSON format, and convert to HTML in the JS code in the browser?

`refresh.py` would output a JSON file `veggiemap-data.json` and `veggiemap.js` would fetch it and make the Leaflet calls that `veggiemap-data.js` currently does.

After this, all the data would be available in `veggiemap.js` to implement opening times, additional search features etc. Or do you see reasons why this would not be preferable?

**Comment by KristjanESPERANTO** [comment]
I would really like it if we switch to JSON. I do not see any disadvantages in it.

**Comment by tuukka** [comment]
Do you want to support IE? IE 10-11 could be supported by including t polyfills would need to be included: https://github.com/github/fetch and https://github.com/taylorhakes/promise-polyfill

**Comment by piratenpanda** [comment]
Also no objections from my side

**Comment by KristjanESPERANTO** [comment]
IE support would be nice, but is not very important on my view.

**Comment by KristjanESPERANTO** [comment]
I created a [new brach](https://github.com/KristjanESPERANTO/veggiekarte/tree/testing-geojson) in which the data is stored as geojson :smiley: It's working, but the first load is very slow (more than 10 seconds) - you can see this [here](https://kristjanesperanto.github.io/veggiekarte/). Does anyone have an idea how to accelerate this?

**Comment by tuukka** [comment]
Thanks @KristjanESPERANTO! I missed this comment and progress of yours. I made some speedups, does it make a difference in your measurements? https://github.com/tuukka/veggiekarte/tree/fix/geojson-speed

**Comment by KristjanESPERANTO** [comment]
Amazing! With that, it's just under 3 seconds. Given how much data there is, that is a small amount of time. I have measured several times and it seems that your version is just as fast as the current version (without geojson). So we can tread this path of Geojson 🥳. Thank you so much!

I will analyze your code more closely within the next few days 🙂

By the way: I like the new tooltip style 👍 But I still don't see which "pointing triangle" you are hiding.

**Comment by tuukka** [comment]
I'm glad to help! With "pointing triangle", I mean the white "tip of the tooltip" which appears between Leaflet's tooltip and the marker if I don't override the CSS rule:
![image](https://user-images.githubusercontent.com/76985/100547646-960b9700-3270-11eb-880f-afb69f556a42.png)

The diff grew larger with more changes than I originally intended to include in one commit:
1. Calculate the popup and tooltip when the user opens them, not while loading the page. This way, there is no need for thousands of them. (The change in tooltip style is a side effect of this.)
2. Remove the use of L.geoJson and eval, as they are not strictly necessary.
3. Add all the markers of a subgroup (vegan_only/vegetarian_friendly/...) in one call to reduce the amount of subgroup re-processing.
4. Reveal all the markers and subgroups at once at the end of loading to reduce the amount of cluster re-calculation.

Let me know if you prefer these changes split into separate commits, more comments in the code etc.

**Comment by KristjanESPERANTO** [comment]
So, we switched to GEOJSON 🥳 Thanks @tuukka. Apparently the new version is now a bit slower. Tukka has already opened an issue (#48) on this subject.

I suggest that we close this issue and care about the speed up in new issues (HTTP/2 and minimize the data is now in my mind).

**Comment by tuukka** [comment]
I suppose I can close this issue as I originally opened it. Let's continue in new issues!
