### ISSUE TITLE
Store and transfer places.json as gzip compressed

### ISSUE THREAD

**Issue by tuukka** [piratenpanda/veggiekarte#48]
To significantly reduce the amount of data transferred and thus the time on slow network connections, places.json (12 MB) could be additionally written to disk as pre-compressed places.json.gz (1.7 MB). Apache could be configured to respond with places.json.gz and `Content-Encoding: gzip` when a request for places.json includes `Accept-Encoding: gzip`. This would require no changes in veggiemap.js as the browser would automatically uncompress the data.

I was able to configure my Apache for this with the following simple .htaccess file:
```
<Files "*.json.gz">
    AddEncoding gzip .gz
    ForceType application/json
</Files>
```

The uncompressed veggiemap.json should also be renamed as veggiemap.json.json so that Apache's MultiViews will do its trick.

This more explicit configuration setup seems like it could be even better but I haven't tested it: https://ma.ttias.be/pre-compress-content-apache-avoid-compressing-every-request/

**Comment by piratenpanda** [comment]
I followed the directions in the link. So a PR with routines that provide additional gzipped files would be welcome :)

**Comment by tuukka** [comment]
Please see #53 :-)

**Comment by piratenpanda** [comment]
Thanks :)

**Comment by KristjanESPERANTO** [comment]
Seems that the map now stays empty after this PR.

**Comment by tuukka** [comment]
I'll check what's going on...

**Comment by piratenpanda** [comment]
Strange, worked for me after commiting. Now it doesn't

**Comment by piratenpanda** [comment]
Still does. It's just really slow on mobile

**Comment by tuukka** [comment]
The service worker may be interfering. I'm checking the headers with `wget -S --spider --compression=auto` and I'm not seeing `Content-Encoding` and it's not automatically returning the compressed file.

**Comment by tuukka** [comment]
@piratenpanda Can you share the Apache config you use?

**Comment by piratenpanda** [comment]
Sure can do this evening

**Comment by tuukka** [comment]
Works the same way as before for me too. @KristjanESPERANTO, can you get more info why the map stays empty for you?

**Comment by piratenpanda** [comment]
I think I know what I forgot. I think I only added the gzip part to the non https version. Will try to fix this when I am at work

**Comment by piratenpanda** [comment]
Should be added to both versions now. Here is the config file.
[veggiekarte.txt](https://github.com/piratenpanda/veggiekarte/files/5641942/veggiekarte.txt)

**Comment by tuukka** [comment]
AIl http paths seem to redirect to https, so it should be enough to make the configuration only for https.

Regarding the config file, I suppose it now handles CSS and JS but not JSON. Adding something like this should do it:
```
            # Serve gzip compressed JSON files if they exist
            # and the client accepts gzip.
            RewriteCond "%{HTTP:Accept-encoding}" "gzip"
            RewriteCond "%{REQUEST_FILENAME}\.gz" -s
            RewriteRule "^(.*)\.json" "$1\.json\.gz" [QSA]

            RewriteRule "\.json\.gz$" "-" [T=application/json,E=no-gzip:1]
```
And amend the FilesMatch to `<FilesMatch "(\.js\.gz|\.css\.gz|\.json\.gz)$">`

You can test e.g. by running `wget --spider -S --compression=auto https://veggiekarte.de/data/places.min.json` and the response headers should include `Content-Encoding: gzip`, `Content-Type: application/json` and `Content-Length: 2042973` (approximately).

**Comment by tuukka** [comment]
There may be a bug in the original sources as well. If it doesn't start to work otherwise, could you test changing the line `RewriteRule "^(.*)\.js" "$1\.js\.gz" [QSA]` to `RewriteRule "^(.*)\.js$" "$1\.js\.gz" [QSA]` i.e. add the first dollar sign?

**Comment by KristjanESPERANTO** [comment]
It's working now :smiley:  Did you change anything, @piratenpanda?

**Comment by piratenpanda** [comment]
> There may be a bug in the original sources as well. If it doesn't start to work otherwise, could you test changing the line `RewriteRule "^(.*)\.js" "$1\.js\.gz" [QSA]` to `RewriteRule "^(.*)\.js$" "$1\.js\.gz" [QSA]` i.e. add the first dollar sign?

Tried both, still no luck

**Comment by piratenpanda** [comment]
Seems fine now. Can anyone check?

**Comment by tuukka** [comment]
Now I'm not able to download the file: although the other headers seem to be correct, `Content-Length` still has the uncompressed length which hints that the server still tries to send the uncompressed file, (which causes a mismatch).

**Comment by piratenpanda** [comment]
curl -I -H "Accept-Encoding: gzip"  https://veggiekarte.de/data/places.min.json

yields
HTTP/2 200 
date: Fri, 04 Dec 2020 21:49:25 GMT
server: Apache/2.4.29 (Ubuntu)
last-modified: Fri, 04 Dec 2020 21:32:29 GMT
etag: "1f32b3-5b5aa36a4ea52"
accept-ranges: bytes
content-length: 2044595
content-encoding: gzip
vary: Accept-Encoding
content-type: application/json

now

**Comment by piratenpanda** [comment]
wget from above still doesnt.

**Comment by piratenpanda** [comment]
https://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly92ZWdnaWVrYXJ0ZS5kZS9kYXRhL3BsYWNlcy5taW4uanNvbg== also seems to show it's working now

**Comment by tuukka** [comment]
> wget from above still doesnt.

Works for me now!

```
$ wget --spider -S --compression=auto https://veggiekarte.de/data/places.min.json
Spider mode enabled. Check if remote file exists.
--2020-12-04 23:59:22--  https://veggiekarte.de/data/places.min.json
Resolving veggiekarte.de (veggiekarte.de)... 207.154.208.198
Connecting to veggiekarte.de (veggiekarte.de)|207.154.208.198|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Fri, 04 Dec 2020 21:59:22 GMT
  Server: Apache/2.4.29 (Ubuntu)
  Upgrade: h2,h2c
  Connection: Upgrade, Keep-Alive
  Last-Modified: Fri, 04 Dec 2020 21:32:29 GMT
  ETag: "1f32b3-5b5aa36a4ea52"
  Accept-Ranges: bytes
  Content-Length: 2044595
  Content-Encoding: gzip
  Vary: Accept-Encoding
  Keep-Alive: timeout=5, max=100
  Content-Type: application/json
Length: 2044595 (1,9M) [application/json]
Remote file exists.
```

And download produces the correct file:
```
$ wget -S --compression=auto https://veggiekarte.de/data/places.min.json
--2020-12-04 23:56:11--  https://veggiekarte.de/data/places.min.json
Resolving veggiekarte.de (veggiekarte.de)... 207.154.208.198
Connecting to veggiekarte.de (veggiekarte.de)|207.154.208.198|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Fri, 04 Dec 2020 21:56:11 GMT
  Server: Apache/2.4.29 (Ubuntu)
  Upgrade: h2,h2c
  Connection: Upgrade, Keep-Alive
  Last-Modified: Fri, 04 Dec 2020 21:32:29 GMT
  ETag: "1f32b3-5b5aa36a4ea52"
  Accept-Ranges: bytes
  Content-Length: 2044595
  Content-Encoding: gzip
  Vary: Accept-Encoding
  Keep-Alive: timeout=5, max=100
  Content-Type: application/json
Length: 2044595 (1,9M) [application/json]
Saving to: ‘places.min.json’

places.min.json   100%[===================>]   1,95M  4,60MB/s    in 0,4s    

2020-12-04 23:56:12 (4,60 MB/s) - ‘places.min.json’ saved [11135439]

```

**Comment by piratenpanda** [comment]
Don't ask. It was a stupid mistake on my end... Glad it's fine now :)
