### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by Strubbl** [piratenpanda/veggiekarte#5]
Hallo Benjamin, magst du eine Lizenz dem Projekt zuweisen?

**Comment by piratenpanda** [comment]
Ich würde mal sagen, alle Plugins und verwendeten Sachen wie die Projekte halt und meins unter CC-By. Ka wie ich das am schlausten mache, habe mir keine Gedanken bisher diesbezüglich gemacht ;)

**Comment by Strubbl** [comment]
Okok, also wäre es kein Problem, wenn ich was von deinem Code nehme und es unter GPLv3 wieder veröffentliche? Es geht mir hauptsächlich um Codeauszüge aus der refresh.py und index.html, da ich gern etwas analoges bauen würde für Club-Mate. Das wäre dann quasi ein Mashup aus deiner veggiekarte und https://github.com/cccmzwi/matekate - deswegen GPLv3.

**Comment by piratenpanda** [comment]
Ist von https://github.com/xsteadfastx/veganmap und das ursprünglich von https://github.com/prusnak/coinmap was es offenbar nicht mehr gibt :/

**Comment by codedust** [comment]
Auf https://www.gnu.org/licenses/license-list.html gibt es eine schöne Auflistung GPL-Kompatibler Lizenzen.

Bisher habe ich nur GPL-Kompatible Software in diesem Repository gefunden:
- FontAwesome: http://fontawesome.io/license/
- Leaflet: https://github.com/Leaflet/Leaflet/blob/master/LICENSE
- locatecontrol: https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/LICENSE
- markercluster: https://github.com/Leaflet/Leaflet.markercluster
- jQuery: https://github.com/jquery/jquery/blob/master/LICENSE.txt

Den Leaflet Geocoder konnte ich bisher noch nicht so richtig einordnen.

**Comment by piratenpanda** [comment]
Ich denke GPL wird am sinnvollsten sein ja, wenn ich dazu komme werde ich es entsprechend einpflegen

**Comment by KristjanESPERANTO** [comment]
Ich habe mir auch mal einen Überblick über die Lizenzen verschafft (siehe Tabelle). Unter https://choosealicense.com/ gibt es auch eine Hilfe um sich für eine Lizenz zu entscheiden.
Ich plädiere für MIT, finde die GPL aber auch gut. So ganz ohne Lizenz-Angabe ist es jedenfall nicht so optimal.

|software			|license			|source	|
|---				|---				|---	|
|fontawesome		|CC-BY-4.0, OFL-1.1, MIT	|http://fontawesome.io/license/|
|leaflet   			|BSD-2-Clause			|https://github.com/Leaflet/Leaflet/blob/master/LICENSE|
|leaflet.control.geocoder   	|BSD-2-Clause			|https://github.com/perliedman/leaflet-control-geocoder/blob/master/LICENSE|
|leaflet.hash   		|MIT				|https://github.com/mlevans/leaflet-hash/blob/master/LICENSE.md|
|leaflet.locatecontrol  |MIT				|https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/LICENSE|
|leaflet.markercluster  	|MIT				|https://github.com/Leaflet/Leaflet.markercluster/blob/master/MIT-LICENCE.txt|
|jquery   			|MIT				|https://github.com/jquery/jquery/blob/master/LICENSE.txt|

**Comment by KristjanESPERANTO** [comment]
Ich war mal so frei einfach einen Pullrequest bezüglich der Lizenz zu machen um das Thema abzuhaken oder zumindest voranzubringen. Bitte nicht übel nehmen und gern ablehen wenn es die MIT nicht sein soll 🙂

**Comment by piratenpanda** [comment]
Sind @codedust und @xsteadfastx damit einverstanden?

**Comment by piratenpanda** [comment]
@xsteadfastx ist es. @codedust auch?

**Comment by piratenpanda** [comment]
@codedust hast du das hier gelesen?

**Comment by codedust** [comment]
Oh. Nein. Danke für den Ping. Ich persönlich würde zwar die GPL bevorzugen, bin aber mit der MIT License auch einverstanden.

**Comment by KristjanESPERANTO** [comment]
@codedust Danke :smiley:

@piratenpanda Entscheide am besten du ob nun MIT oder GPL :sunglasses:

**Comment by piratenpanda** [comment]
Ich würde eigentlich auch GPL bevorzugen. Wenn du den PR entsprechend modifizieren könntest wäre das super. Danke an alle Beteiligten für die gute Zusammenarbeit hier :)

**Comment by KristjanESPERANTO** [comment]
Prima! Ich habe den PR angepasst (GPL statt MIT) :smiley:

**Comment by piratenpanda** [comment]
Hiermit schließe ich den vier Jahre alten Bug! :)
