### ISSUE TITLE
Switch to HTTP/2

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#50]
The website is now running with HTTP/1.1. Changing to HTTP/2 should improve performance.

I have never switched an Apache server from HTTP/1 to HTTP/2. But I found a relatively new blog post about it in German: https://www.lalber.org/2020/02/apache2-http2-aktivieren/

**Comment by piratenpanda** [comment]
Should be done

**Comment by piratenpanda** [comment]
Please test and report if it's not working. I checked via https://tools.keycdn.com/http2-test

Thanks for the link, was helpful :)

**Comment by KristjanESPERANTO** [comment]
Seems to work 🙂 I stumbled across it because of Lighthouse, now Lighthouse doesn't complain about it anymore.
