### ISSUE TITLE
Show loading spinner or progress bar while icons are being loaded

### ISSUE THREAD

**Issue by piratenpanda** [piratenpanda/veggiekarte#51]
Currently users don't know if there is something happening until the icons are shown so a spinner or progress bar would be nice in my opinion

**Comment by tuukka** [comment]
One way that comes to mind would be to include a spinner CSS or SVG animation as the first thing in index.html and then hide it after the map icons have become visible.

**Comment by KristjanESPERANTO** [comment]
Seeing progress would be nice for the user I think.

Maybe something like this example: https://fetch-progress.anthum.com/fetch-basic/

**Comment by KristjanESPERANTO** [comment]
I tried to add a progress bar, but did not get an acceptable result. So I built in a simple spinner like @tuukka suggested. But I suggest to leave the issue open so that we might add a progress bar later.

**Comment by piratenpanda** [comment]
Moved to https://codeberg.org/piratenpanda/veggiekarte/issues/51
