### ISSUE TITLE
Separate map from icon loading

### ISSUE THREAD

**Issue by piratenpanda** [piratenpanda/veggiekarte#52]
Currently it looks like icon loading blocks loading of map tiles which makes the page look even slower. Can this be fixed somehow?

**Comment by tuukka** [comment]
The blocking is caused by the calculation of the icon clustering. It would be great to do this calculation already on the server (whenever the places.json data is updated.)

**Comment by KristjanESPERANTO** [comment]
Before changing to server side clustering (which would actually be cool, but would be a major change) we could try to change from leaflet.markercluster (which apparently is no longer being developed) to another clustering library.

[Supercluster ](https://github.com/mapbox/supercluster) for example has at least in its description that it is very fast.

**Comment by tuukka** [comment]
> [Supercluster ](https://github.com/mapbox/supercluster) for example has at least in its description that it is very fast.

Great idea, and if you use it with a worker like in this example, it does not block the main thread while calculating: https://github.com/mapbox/supercluster/tree/main/demo

**Comment by tuukka** [comment]
@KristjanESPERANTO Did you have a look at integrating supercluster yet? If not, I might have time now.

**Comment by KristjanESPERANTO** [comment]
@tuukka I started, but stumbled upon the use of the categories and therefore didn't get any further. It would be nice if you could look at it.

**Comment by tuukka** [comment]
I haven't had enough time for this yet, but what I have this far seems at least promising (clustering takes less than a second now as opposed to more than 5 seconds before): https://github.com/tuukka/veggiekarte/tree/feat/quick-clustering

For categories, perhaps it's ok to have a 1-second delay and recalculate completely when a category is toggled?

Animations are still completely missing, but it probably makes more sense to re-implement them with supercluster than try to adapt Leaflet.markercluster.

**Comment by KristjanESPERANTO** [comment]
This is nice :slightly_smiling_face:! And I see you try another version of markercluster as well.

I think it's a good approach to add all the markers at once and take care of the filtering when the user selects a filter. We need more filters anyway and the current filtering per subgroup is not suitable for multiple filters, I think.

Which animations are missing?

**Comment by piratenpanda** [comment]
Moved to https://codeberg.org/piratenpanda/veggiekarte/issues/52
