### ISSUE TITLE
Show if open or closed

### ISSUE THREAD

**Issue by piratenpanda** [piratenpanda/veggiekarte#6]

**Comment by KristjanESPERANTO** [comment]
With #33 we will have the opening hours, but this is only the first step. To show if a location is open or not, needs a more difficult solution.

A filter to hide closed locations also would be nice.

**Comment by tuukka** [comment]
To not slow down the page load, perhaps this might be best to calculate on the server every hour?

The result of the calculation could be the current status (open/closed) plus the time when the status next changes. This way, the UI can switch the marker immediately when the change happens and also show warnings like "closes in 20 minutes".

**Comment by KristjanESPERANTO** [comment]
Perhaps it would make sense to offer this function only from a certain zoom level. Then performance would not be such a problem.

**Comment by piratenpanda** [comment]
Moved to https://codeberg.org/piratenpanda/veggiekarte/issues/6
