### ISSUE TITLE
Link to instruction doesn't work

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#61]
The link to the instruction [1] doesn't work anymore. The whole website appears to be empty.

Will the content be available again or should we look for an alternative instruction?

[1] https://www.lebsanft.org/posts/informationen-zur-veggiekarte-hinzufuegen/

**Comment by piratenpanda** [comment]
Will take a look tomorrow. I totally forgot about that

**Comment by KristjanESPERANTO** [comment]
Thank you :slightly_smiling_face: 

We could put the instruction here in a separate HTML file. That would make it independent of your blog.

**Comment by piratenpanda** [comment]
Added a very basic one with https://github.com/piratenpanda/veggiekarte/commit/12945903c55bbefb89e6e7778c7893a71d89650a

**Comment by KristjanESPERANTO** [comment]
Nice :+1:
