### ISSUE TITLE
Thanks to all the contributors

### ISSUE THREAD

**Issue by piratenpanda** [piratenpanda/veggiekarte#67]
As I don't know any other way, please find my sincerest thanks for improving on my initial work and guiding the project to where it is now :) Hope you all have a wonderful 2021!
@KristjanESPERANTO @tuukka @codedust

**Comment by KristjanESPERANTO** [comment]
This is nice, thank you. I like this project and I wish you and the others a great new year too! 🎉

Perhaps the new "Discussions" feature for GitHub projects would be suitable for this. Can you activate this via the settings? This could also be a good place to discuss new ideas or get feedback from users.

**Comment by piratenpanda** [comment]
Ah nice feature, didn't know about it. It should be enabled now

**Comment by codedust** [comment]
Thanks a lot for your nice words! It feels nice to receive an appreciation like this. And thanks for starting this wonderful project! :tada: :heart:

**Comment by piratenpanda** [comment]
Thanks also go to @xsteadfastx of course :)

**Comment by tuukka** [comment]
Thank you @piratenpanda, @KristjanESPERANTO, @codedust for the nice project! I hope you have had a good beginning of 2021. At least the project is improving faster than I'm able to follow :rocket:
