### ISSUE TITLE
Have different filter options to select

### ISSUE THREAD

**Issue by turion** [piratenpanda/veggiekarte#7]
It would be cool if one could filter on tags like diet:vegan=only and diet:vegetarian=only, and possibly on other information (e.g. café, bakery, restaurant, pub etc.).

**Comment by piratenpanda** [comment]
Would indeed be nice, I'm open for contributions as my time is very limited currently unfortunately

**Comment by piratenpanda** [comment]
implemented with the latest pull request

**Comment by turion** [comment]
Awesome!
