### ISSUE TITLE
Disable Directory Listing

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#72]
It's nice to have Directory Listing enabled for testing or debugging and in our case it's maybe not dangerous [1]. Nevertheless I think that it should be switched off to be on the safe side.

[1] https://www.acunetix.com/blog/articles/directory-listing-information-disclosure/

**Comment by piratenpanda** [comment]
done

**Comment by KristjanESPERANTO** [comment]
Strange. I still can access the directory: https://veggiekarte.de/data/

**Comment by piratenpanda** [comment]
Yeah because I was stupid. Will be fixed soon

**Comment by piratenpanda** [comment]
Should be fixed

**Comment by KristjanESPERANTO** [comment]
Yes :+1: :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
Directory Listing is enabled again.

**Comment by piratenpanda** [comment]
Whatever happened. I now removed the autoindex mod so we'll never run into this again...

**Comment by piratenpanda** [comment]
Thanks for spotting this
