### ISSUE TITLE
GZIP compression by default

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#77]
Can we enable GZIP compression by default?

Here is an article about the why and the how: https://betterexplained.com/articles/how-to-optimize-your-site-with-gzip-compression/

This is the recommendation from this article:

```
AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/css
AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript
```

xml, xhtml and rss we don't need, I think.

But in our case, it would be good if JSON were also added:
```
AddOutputFilterByType DEFLATE application/json
```

If this is possible, we don't have to gzip the places file in the python script anymore :slightly_smiling_face:

**Comment by piratenpanda** [comment]
thanks and done
