### ISSUE TITLE
No new data since last PR

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#79]
The map still contains the data from January 31st. This is the data from the last PR #78.

I can run the `refresh.py` successfully, so I think most likely it is because of the Python version on the server. Is it older than 3.4? Since version 3.4 `pathlib` is included in Python.

Can you see any error messages when you run it manually?

**Comment by piratenpanda** [comment]
I added an encoding header as it was complaining. Don't know why this was necessary but now it works it seems

**Comment by KristjanESPERANTO** [comment]
Interesting, I thought this was no longer necessary for Python 3: https://stackoverflow.com/questions/14083111/should-i-use-encoding-declaration-in-python-3/14083123#14083123

**Comment by piratenpanda** [comment]
Maybe I messed something up on my machine. I don't know. I can try without again

**Comment by piratenpanda** [comment]
Yeah, works fine

**Comment by piratenpanda** [comment]
Strange, so maybe some cron issue. Let's keep an eye on it

**Comment by KristjanESPERANTO** [comment]
There is no new data since 3 days. Seems there is another problem.
