### ISSUE TITLE
No new data

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#86]
The update of the data still does not work. It is probably the same cause as from issue #79.

**Comment by piratenpanda** [comment]
Cron is running just fine each 30mins, maybe we should add some debug output to the python script

**Comment by piratenpanda** [comment]
The sum the script returns does not match the sum of items shown for the layers

**Comment by piratenpanda** [comment]
stat file shows the correct numbers

**Comment by piratenpanda** [comment]
I wonder why the stat file doesn't show stats for each day. Shouldn't it create the file for each day?

**Comment by piratenpanda** [comment]
I think I found the problem

**Comment by KristjanESPERANTO** [comment]
Yes, an entry should be added to the stat file on the server every day. This doesn't seem to work at the moment when the script is executed via a cron job.

Regardless of the current problem, there are also gaps in the stat file beforehand because it is overwritten with the old version from the repository with every update. I will open a new issue for that.

> I think I found the problem

Great, I'm curious.

**Comment by piratenpanda** [comment]
> Great, I'm curious.

I was running the refresh script via an absolute path and the data path in the script is a relative one so when the cronjob ran it obviously doesn't find ~/data. I made a new bash script running the script now inside the correct folder. Should fix this once and for all
