### ISSUE TITLE
Avoid overwriting the stat.json

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#87]
With every update, the `stat.json` is overwritten with an older version during the upload process to the server. This is a pity as this file is updated every day and we lost a lot of statistical information.

How can we avoid  that the `stat.json` is not overwritten during the upload process?

**Comment by piratenpanda** [comment]
This might be due to my git incompetence. Will try to take a look next time

**Comment by tuukka** [comment]
Could `stat.json` be written by a separate script or command line option that would only be used on the server? This way, `git pull` on the server would never bring in conflicting updates made elsewhere. 

Perhaps the best solution might be to remove `stat.json` from version control if the stats would be (re-)calculated based on OSM's history (#74).

**Comment by tuukka** [comment]
Script to (re-)generate statistics history here: #88.

**Comment by piratenpanda** [comment]
Thanks, I removed stat.json now from version control and added the stat script to the other script. Might be overkill to do this all 30mins though
