### ISSUE TITLE
stat.json is sometimes empty

### ISSUE THREAD

**Issue by KristjanESPERANTO** [piratenpanda/veggiekarte#92]
Since the query of the historical data sometimes doesn't work, we have to prevent the previous `stat.json` from being overwritten with an empty version. We already have something like that in the `refresh.py` in case we don't get proper data from OSM.

**Comment by piratenpanda** [comment]
Should be fixed with https://github.com/piratenpanda/veggiekarte/commit/d7c74c09e40b23ef3214c661a27ce0bbc035bbeb hopefully

**Comment by piratenpanda** [comment]
I need to take a closer look at this

**Comment by piratenpanda** [comment]
Fixed with https://github.com/piratenpanda/veggiekarte/commit/cbf172bb05eb717b6860d4c8ab11d1fdc79699c4

**Comment by KristjanESPERANTO** [comment]
Looks good 👍

**Comment by piratenpanda** [comment]
Now we just need ohsome to work again :D

**Comment by tuukka** [comment]
Hmm, Ohsome should be working again - are you still not able to get results back? In any case it's a somewhat slow and heavy process so what do you think of only fetching the data from them in special cases (to restore the history) and doing the (hourly) updates with Overpass?

**Comment by KristjanESPERANTO** [comment]
I think that makes sense. So we are not so dependent on a third party. Just to close the gaps if necessary. I could reinstall the old functionality. But let's wait and see what @piratenpanda says :-)

**Comment by piratenpanda** [comment]
Do we really need hourly stats? I could move the ohsome cron job to weekly maybe? But I don't have a strong opinion on that

**Comment by KristjanESPERANTO** [comment]
An ohsome query once a week would also be okay I think. But then the numbers in the Layer Control are not always up to date.

We could combine both. The update of the `stat.json` like before and then the weekly ohsome cronjob to fill gaps.

![Bildschirmfoto von 2021-03-08 20-05-21](https://user-images.githubusercontent.com/35647502/110369351-9626ea00-804a-11eb-8807-b6a154e2142f.png)

**Comment by piratenpanda** [comment]
crontab has been changed accordingly. Now moving stat file generation back into update.py

**Comment by piratenpanda** [comment]
Doing final testing. I noticed ohsome returns only data up to the end of february. Is this some ohsome bug or an issue on our side? I didn't find an end date so I assume the former.

**Comment by piratenpanda** [comment]
everything should be in place now

**Comment by tuukka** [comment]
> I noticed ohsome returns only data up to the end of february. Is this some ohsome bug or an issue on our side?

It seems that they don't update their data every day or even every week.
